# Pulls image including:
#   Python 3.72, incl. pip and pipenv
#   Pandoc 2.11.3
#   pandoc-crossref 0.3.8.4
#   pandoc-include 0.8.4
# Builds html from md file, copies to public

image: kenose/pandoc-python:latest

build:
  script:
    - cd docs
    - pandoc --filter pandoc-include --filter pandoc-crossref --citeproc --bibliography=dep/appendix.bib --csl=dep/journal-of-family-research.csl --number-sections --table-of-contents -c dep/empty.css -H dep/vue_extended_h.css appendix.md -H dep/lightbox.js -s -o appendix.html
    - cp appendix.html index.html
    - python dep/relpathfix.py 'index.html' '../results/figures' 'figures' # fix links for pages
    - mv index.html ../public/
    - ls
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git add docs/appendix.html
    - git add public/index.html
    - git commit -m "[ci skip] Built docs ${CI_COMMIT_TAG}"
    - git push http://${GITLAB_USER_LOGIN}:${TOKEN}@scm.cms.hu-berlin.de/${CI_PROJECT_PATH} HEAD:${CI_COMMIT_REF_NAME}
  only:
    - master

pages:
  script:
    - cp -R -f results/figures/ ../public/ # copy figures
  artifacts:
    paths:
      - public
    expire_in: 5 mins
  only:
    - master
