# Pulls image including:
# - Python 3.72 incl. pip
# - pandoc-include 0.8.4
# - Pandoc 2.11.3
# - pandoc-crossref 0.3.8.4
#
#
# - Builds self-contained html from md file (needs dependencies in dep)
# - Commits generated file to docs and public
# - Public populates pages

image: kenose/pandoc-python:latest

before_script:
  - export DATE=$(date '+%y-%m-%d')

build:
  script:
    - cd docs
    - >-
      python3 dep/regexrep.py 'appendix.md' '(subtitle:[\s][\S])\b.*$' 'subtitle: "Version <b>${CI_COMMIT_TAG}</b>"' # set version in yaml header of doc
    - >-
      python3 dep/regexrep.py 'appendix.md' '(date:[\s][\S])\b.*$' 'date: "${DATE}<hr>"' # set date in yaml header of doc
    - pandoc --filter pandoc-include --filter pandoc-crossref --citeproc --bibliography=dep/appendix.bib --csl=dep/journal-of-family-research.csl --number-sections --table-of-contents -c dep/empty.css -H dep/vue_extended_h.css appendix.md -H dep/lightbox.js -s -o appendix.html
    - cp appendix.html index.html
    - python3 dep/regexrep.py 'index.html' '../results/figures' 'figures' # fix links for pages (though usually no problem with base64 encoded .svg)
    - mv index.html ../public/
    - cd ../
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git checkout master
    - git add docs/appendix.md
    - git add docs/appendix.html
    - git add public/index.html
    - git commit -m "[ci skip] Built docs ${CI_COMMIT_TAG}"
    - git pull --rebase http://${GITLAB_USER_LOGIN}:${TOKEN}@scm.cms.hu-berlin.de/${CI_PROJECT_PATH} HEAD:${CI_COMMIT_REF_NAME}
    - git push http://${GITLAB_USER_LOGIN}:${TOKEN}@scm.cms.hu-berlin.de/${CI_PROJECT_PATH} HEAD:${CI_COMMIT_REF_NAME}
  only:
    - master

pages:
  stage: deploy
  script:
    - cp -R -f results/figures/ public/ # copy figures
  artifacts:
    paths:
      - public
    expire_in: 15 mins
  only:
    - master
