# Pulls image including:
#   Python 3.72, incl. pip and pipenv
#   Pandoc 2.11.3
#   pandoc-crossref 0.3.8.4
#   pandoc-include 0.8.4
# Builds html from md file, copies to public

image: kenose/pandoc-python:latest

cache:
  paths:
    - .cache/pip

before_script:
  - python -V  # Print out python version for debugging

pages:
  script:
    - cd docs
    - pandoc --filter pandoc-include --filter pandoc-crossref --citeproc --bibliography=dep/appendix.bib --csl=dep/journal-of-family-research.csl --number-sections --table-of-contents -c dep/empty.css -H dep/vue_extended_h.css appendix.md -H dep/lightbox.js -s -o appendix.html
    - cp appendix.html index.html ../public/
    - mv index.html ../public/
  artifacts:
    paths:
      - public
  only:
    - master
