# Pulls image including:
# - Python 3.72 incl. pip
# - pandoc-include 0.8.4
# - Pandoc 2.11.3
# - pandoc-crossref 0.3.8.4
#
#
# - Builds self-contained html from md file (needs dependencies in dep)
# - Commits generated file to docs and public
# - Public populates pages

image: kenose/pandoc-python:latest

before_script:
  - export DATE=$(date '+%Y-%m-%d')

gen_docs:
  stage: build
  script:
    - cd docs
    - python3 dep/regexrep.py 'appendix.md' '(subtitle:[\s])(.*)' '\1"Version <b>' ${CI_COMMIT_TAG} '</b>"'
    - python dep/regexrep.py 'appendix.md' '(date:[\s])(.*)' '\1"' ${DATE} '"'
    - pandoc --filter pandoc-include --filter pandoc-crossref --citeproc --bibliography=dep/appendix.bib --csl=dep/journal-of-family-research.csl --number-sections --table-of-contents -c dep/empty.css -H dep/vue_extended_h.css appendix.md -H dep/lightbox.js -s -o appendix.html
    - cd ../
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git add docs/appendix.md
    - git add docs/appendix.html
    - git commit -m "Document build ${CI_COMMIT_TAG} [ci skip]" || echo "Nothing to commit."
    - git remote show origin
    - git remote rm origin && git remote add origin http://${GITLAB_USER_LOGIN}:${TOKEN}@scm.cms.hu-berlin.de/${CI_PROJECT_PATH}
    - git push origin :refs/tags/${CI_COMMIT_TAG}
    - git push origin master:refs/heads/${CI_COMMIT_REF_NAME} --tags
  only:
    - tags

pages:
  stage: deploy
  script:
    - git pull --rebase http://${GITLAB_USER_LOGIN}:${TOKEN}@scm.cms.hu-berlin.de/${CI_PROJECT_PATH}
    - rm -rf public
    - mkdir public
    - cp -R -f results/figures/ public # copy figures
    - cd docs
    - cp appendix.html index.html
    - python3 dep/regexrep.py 'index.html' '../results/figures' 'figures' # fix links for pages (though usually no problem with base64 encoded .svg)
    - mv index.html ../public # copy index to update
  artifacts:
    paths:
      - public
    expire_in: 15 mins
  only:
    - tags
